name: Daily Scrape

on:
    schedule:
        - cron: "0 0 * * *" # Runs daily at midnight
    push:
        branches:
            - main # Specify the branch to trigger the workflow on push

jobs:
    scrape:
        runs-on: ubuntu-latest

        env:
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.13.1" # Specify the Python version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Install GeckoDriver
              run: |
                  sudo apt-get update
                  sudo apt-get install -y firefox-geckodriver

            - name: Run scrape script
              run: |
                  python src/scrape.py
